### ISSUE TITLE
varints in NetStream-Manual

### ISSUE THREAD

**Issue by Falco20019** [graphstream/gs-netstream#5]
The [NetStream-Manual wiki page](https://github.com/graphstream/gs-netstream/wiki/NetStream-Manual) is still missing the information that you have to use varints for the current receiver to work with the implementation. Or at least add an information to the wiki that it is not up2date or that you have to use the older version of the core. It took me some time to figure this out and to find the closed issue.

**Comment by pigne** [comment]
Indeed. Sorry about that. I'll update the doc.

**Comment by pigne** [comment]
Updated.
